### ISSUE TITLE
clang 12 fails to compile wxWidgets with multiple CF bridge errors

### ISSUE THREAD

**Issue by ancwrd1** [tpoechtrager/osxcross#274]
I've created osxcross toolchain based on clang 12 and tried to build the wxWidgets with it. However a few compilation errors occur:

```
In file included from /wx/wxWidgets/src/osx/cocoa/appprogress.mm:11:
In file included from /wx/wxWidgets/include/wx/osx/private.h:4:
In file included from /wx/wxWidgets/include/wx/osx/core/private.h:20:
/wx/wxWidgets/include/wx/osx/core/cfstring.h:46:71: error: ObjectiveC object of type 'WX_NSString' (aka 'NSString *') is bridged to 'CFStringRef' (aka 'const __CFString *'), which is not valid CF object
        : wxCFRef< CFStringRef >((WX_OSX_BRIDGE_RETAINED CFStringRef) ref)
                                                                      ^
/osxcross/bin/../SDK/MacOSX11.1.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:463:1: note: declared here
typedef const struct CF_BRIDGED_TYPE(NSString) __CFString * CFStringRef;
^
In file included from /wx/wxWidgets/src/osx/cocoa/appprogress.mm:11:
In file included from /wx/wxWidgets/include/wx/osx/private.h:4:
In file included from /wx/wxWidgets/include/wx/osx/core/private.h:20:
/wx/wxWidgets/include/wx/osx/core/cfstring.h:74:72: error: CF object of type 'CFStringRef' (aka 'const __CFString *') is bridged to 'NSMutableString', which is not an Objective-C class
    WX_NSString AsNSString() const { return (WX_OSX_BRIDGE WX_NSString)(CFStringRef) *this; }
                                                                       ^
/osxcross/bin/../SDK/MacOSX11.1.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:463:1: note: declared here
typedef const struct CF_BRIDGED_TYPE(NSString) __CFString * CFStringRef;
^
In file included from /wx/wxWidgets/src/osx/cocoa/appprogress.mm:11:
In file included from /wx/wxWidgets/include/wx/osx/private.h:4:
In file included from /wx/wxWidgets/include/wx/osx/core/private.h:20:
/wx/wxWidgets/include/wx/osx/core/cfstring.h:99:60: error: ObjectiveC object of type 'NSString *' is bridged to 'CFStringRef' (aka 'const __CFString *'), which is not valid CF object
    return wxCFStringRefFromGet((WX_OSX_BRIDGE CFStringRef)p);
                                                           ^
/osxcross/bin/../SDK/MacOSX11.1.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:463:1: note: declared here
typedef const struct CF_BRIDGED_TYPE(NSString) __CFString * CFStringRef;
^
```

Is it something clang-specific? I've asked wxWidgets guys but they have no idea.

The `WX_OSX_BRIDGE_RETAINED` is defined as follows:

```c++
#if __has_feature(objc_arc)
#define WX_OSX_BRIDGE_RETAINED __bridge_retained
#define WX_OSX_BRIDGE __bridge
#else
#define WX_OSX_BRIDGE_RETAINED
#define WX_OSX_BRIDGE
#endif
```

**Comment by tpoechtrager** [comment]
It must be their code that's broken because it builds with *10.13* SDK and clang 10.0.

**Comment by ancwrd1** [comment]
Yes it also worked perfectly well with SDK 11.1 and clang 11. But since I've upgraded clang on openSUSE Tumbleweed (from 11 to 12) it's broken, so the question is could be it be some clang compiler configuration that breaks ObjC/CF bridge or something like that. Unfortunately I am not very familiar with clang internals.

**Comment by tpoechtrager** [comment]
It's most likely the code that's broken not clang. You must downgrade to LLVM/Clang 11.0 or fix the code somehow.

**Comment by ancwrd1** [comment]
Something was changed in clang 12 which now requires the "#import <Foundation/Foundation.h>" in the ObjectiveC files. So you are right, it's not a osxcross issue.
